// <auto-generated />
namespace COCOMO_II_MODEL_BY__OBILOR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Aug27a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aug27a));
        
        string IMigrationMetadata.Id
        {
            get { return "201808271214551_Aug27a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
