// <auto-generated />
namespace COCOMO_II_MODEL_BY__OBILOR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Aug27b1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aug27b1));
        
        string IMigrationMetadata.Id
        {
            get { return "201808271427196_Aug27b1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
